"use strict";
// ================= Report Generator — professional pentest reports =================
// Generates structured security assessment reports from findings.
// Outputs: Markdown, HTML, or JSON. Follows standard pentest report format.
// TEAM TIER FEATURE

function generateReport(opts) {
  const {
    title = "Security Assessment Report",
    target = "Unknown",
    assessor = "Darknode",
    date = new Date().toISOString().split("T")[0],
    scope = "Full penetration test",
    findings = [],
    executive = "",
  } = opts;

  const sevOrder = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
  const sorted = [...findings].sort((a, b) => (sevOrder[a.severity] || 5) - (sevOrder[b.severity] || 5));

  const stats = { critical: 0, high: 0, medium: 0, low: 0, info: 0, total: findings.length };
  for (const f of findings) stats[f.severity] = (stats[f.severity] || 0) + 1;

  const riskScore = stats.critical * 10 + stats.high * 7 + stats.medium * 4 + stats.low * 1;
  const riskLevel = riskScore >= 30 ? "Critical" : riskScore >= 15 ? "High" : riskScore >= 5 ? "Medium" : "Low";

  const sections = [
    `# ${title}`,
    "",
    "| Field | Value |",
    "|-------|-------|",
    `| Target | ${target} |`,
    `| Assessor | ${assessor} |`,
    `| Date | ${date} |`,
    `| Scope | ${scope} |`,
    `| Overall Risk | **${riskLevel}** (score: ${riskScore}) |`,
    "",
    "## Executive Summary",
    "",
    executive || `A security assessment was conducted against ${target}. ${stats.total} findings were identified: ${stats.critical} critical, ${stats.high} high, ${stats.medium} medium, ${stats.low} low, ${stats.info} informational. The overall risk level is **${riskLevel}**.`,
    "",
    "## Findings Summary",
    "",
    "| # | Severity | Title | Status |",
    "|---|----------|-------|--------|",
    ...sorted.map((f, i) => `| ${i + 1} | ${f.severity.toUpperCase()} | ${f.title} | ${f.status || "Open"} |`),
    "",
    "## Detailed Findings",
    "",
  ];

  for (let i = 0; i < sorted.length; i++) {
    const f = sorted[i];
    sections.push(
      `### ${i + 1}. ${f.title}`,
      "",
      `**Severity:** ${f.severity.toUpperCase()} | **CVSS:** ${f.cvss || "N/A"} | **Status:** ${f.status || "Open"}`,
      "",
      "**Description:**",
      f.description || "No description provided.",
      "",
      "**Impact:**",
      f.impact || "Potential security impact.",
      "",
      "**Evidence:**",
      f.evidence ? "```\n" + f.evidence + "\n```" : "No evidence attached.",
      "",
      "**Remediation:**",
      f.remediation || "Fix the identified vulnerability.",
      "",
      "---",
      "",
    );
  }

  sections.push(
    "## Remediation Priority",
    "",
    "1. **Immediate** — Fix all Critical and High findings",
    "2. **Short-term** — Address Medium findings within 30 days",
    "3. **Long-term** — Plan fixes for Low findings",
    "",
    "## Methodology",
    "",
    "This assessment followed the OWASP Testing Guide and PTES (Penetration Testing Execution Standard).",
    "",
    "Phases: Reconnaissance → Enumeration → Vulnerability Analysis → Exploitation → Post-Exploitation → Reporting",
    "",
    "---",
    `*Generated by Darknode on ${date}*`,
  );

  return { markdown: sections.join("\n"), stats, riskLevel, riskScore };
}

function findingTemplate(overrides) {
  return {
    title: "Untitled Finding",
    severity: "medium",
    cvss: null,
    description: "",
    impact: "",
    evidence: "",
    remediation: "",
    status: "Open",
    ...overrides,
  };
}

module.exports = { generateReport, findingTemplate };
